name: 'triggers - exercice 2'

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - run: echo "je vérifie que le code compile bien"