on: 
  workflow_dispatch:
    

jobs:
  job1:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: echoing
        run: echo 'Hello there'
