name: "ex - secrets"
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lgmorand/github-action-hello@v1
        with:
          firstname: ${{ secrets.MON_SECRET }}