name: "triggers - exercice 3"

on:
  pull_request:
    paths: 
    - "**yml"
    - "!**/test/**yml"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - run: echo "je vérifie les fichiers YAML"
