name: "matrix - ex 1"
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [4.2.x, 5.0.x]
        buildMode: [Debug, Release]
  
    steps:
      - name: Récupère le code source
        uses: actions/checkout@v2
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.buildMode }}
        env:
          buildMode: $ {{ matrix.buildMode }}
      