name: "matrix FA"
on: workflow_dispatch

jobs:
  matrix_job_ex:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [10, 12]
        include:
          - os: macos-latest
            node: 8
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}