name: "ex-env"
on: workflow_dispatch

jobs:
  Dev:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
    - run: echo "Hello"
  Test:
    runs-on: ubuntu-latest
    environment:
      name: Test de charge
    steps:
    - run: echo "Hello"
