name: container_test

on:
  workflow_dispatch:

jobs:
  container_test_job:
    runs-on: ubuntu-latest
    container: 'node:current'
  
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run build