name: testing_dynamic_var

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VARIABLE: jaune
    steps:
    - run: echo ${{ env.VARIABLE }}
    - run: |
        echo "VARIABLE=vert" >> $GITHUB_ENV
        echo ${{ env.VARIABLE }}
    - run: echo ${{ env.VARIABLE }}