name: vars - ex1

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VAR1: hello
    steps:
      - run: echo "VAR2=${{ env.VAR1 }}" >> $GITHUB_ENV
      - run: echo $VAR2

