name: vars - ex2

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Just-testing-time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: DD/MM/YYYY
      - name: print-current-time
        run: echo ${{ steps.current-time.outputs.formattedTime }}
