name: workflow with var

on:
  workflow_dispatch:
    inputs:
      myParam:
        description: 'My first param'
        required: true
        default: 'hello'
      myParam2:
        description: 'My second param'
        required: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event.inputs.myParam}}" "${{github.event.inputs.myParam2}}"
